# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: control-plane
version: '0.0.0'
github: "kleidukos/control-plane"
license: MIT
author: "Kleidukos"
maintainer: "Kleidukos"
# synopsis: A new Ultimaskel package.
# description: control-plane is a new Ultimaskel package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - DuplicateRecordFields 
  - EmptyCase
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators

when:
  - condition: "impl(ghc >= 8.4.4)"
    then:
      ghc-options:
        - -Wall
        - -Wcompat
        - -Werror
        - -Widentities
        - -Wincomplete-record-updates
        - -Wincomplete-uni-patterns
        - -Wpartial-fields
        - -Wredundant-constraints
        - -fhide-source-paths
        - -Wno-unused-do-bind
    else:
      ghc-options:
        - -Wall
        - -Wcompat
        - -Werror
        - -Widentities
        - -Wincomplete-record-updates
        - -Wincomplete-uni-patterns
        - -Wredundant-constraints
        - -fhide-source-paths
        - -Wno-unused-do-bind

library:
  dependencies:
  - aeson
  - base-noprelude
  - colourista
  - envparse
  - mtl
  - password
  - postgresql-simple
  - postgresql-simple-migration
  - relude
  - resource-pool
  - servant
  - servant-auth-server
  - servant-server
  - text
  - time
  - unordered-containers
  - uuid
  - vector
  - wai
  - warp
  source-dirs: src

executables:
  control-plane-routes:
    source-dirs: app/layout
    main: Main.hs
    dependencies:
    - base-noprelude
    - control-plane
    - relude
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
  control-plane-server:
    source-dirs: app/server
    main: Main.hs
    dependencies:
    - base-noprelude
    - control-plane
    - relude
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  control-plane-test:
    source-dirs: test
    main: Main.hs
    dependencies:
    - aeson
    - aeson-pretty
    - base-noprelude
    - control-plane
    - hspec
    - relude
    - string-qq
    - time
    - uuid
