export DB_HOST="localhost"
export DB_PORT="5432"
export DB_USER="postgres"
export DB_PASSWORD="postgres"
export DB_DATABASE="control_plane_dev"
export DB_POOL_CONNECTIONS="10"
export DB_SUB_POOLS="10"
export DB_TIMEOUT="10"
